apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: http-headers
spec:
  selector:
    matchLabels:
      app: httpbin
  url: xcbeyond/wasm-extensions/http-headers:1.0.0
  phase: AUTHN
  pluginConfig:
    headers: x-wasm-header
    value: wasm-demo
  